<a href="https://colab.research.google.com/github/rao-mukul/AI-ML-Course/blob/main/NumPyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [20]:
b = np.array([9,8,6.9,7.5])
print(b)

[9.  8.  6.9 7.5]


In [21]:
c = a + b
print(c)

[10.  10.   9.9 11.5]


In [22]:
c.sort()
print(c)

[ 9.9 10.  10.  11.5]


In [26]:
d = np.array([[1,2,3],[4,5,6]], dtype = int)
print(d)

[[1 2 3]
 [4 5 6]]


In [24]:
e = np.array([[8,2,10],[35,7,99]], dtype = float)
print(e)

[[ 8.  2. 10.]
 [35.  7. 99.]]


In [27]:
d + e

array([[  9.,   4.,  13.],
       [ 39.,  12., 105.]])

In [29]:
f = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(f)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [33]:
g = np.zeros((3,3),dtype=int)
print(g)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
h = np.ones((4,5),dtype=int)
print(h)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [38]:
i = np.arange(10,25,5) # This is a range, it gives us a range from 10 to 25 taking steps of 5
# lower limit included , Upper Limit not included
print(i)

[10 15 20]


In [45]:
j = np.linspace(0,4,5).astype(int)
print(j)

[0 1 2 3 4]


In [46]:
k = np.full((2,2),7)
print(k)

[[7 7]
 [7 7]]


In [48]:
l = np.eye(2).astype(int)   # It creates an indentity matrix
print(l)

[[1 0]
 [0 1]]


In [61]:
m = np.random.random((2,2)).astype(float)
print(m)

[[0.60818758 0.22102017]
 [0.73973865 0.76158766]]


In [62]:

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Save the array to a file named 'my_array.npy'
np.save('my_array', arr)


In [63]:
!ls

my_array.npy  sample_data


In [64]:
loaded_array = np.load('my_array.npy')
print(loaded_array)

[1 2 3 4 5]


In [65]:
%pwd


'/content'

In [67]:
pwd

'/content'

In [69]:
np.int64

numpy.int64

**Inspecting Array**

In [85]:
ar = np.array([[1,2,3,4,5],[5,6,7,8,9]])
# print(ar)
ar.shape
len(ar)
a.ndim
a.size
a.dtype

dtype('int64')